# Generated by Django 5.2.17 on 2026-09-25 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Título del contenido en el momento de la compra.', max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('moneda', models.CharField(default='eur', max_length=3)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada'), ('reembolsada', 'Reembolsada'), ('caducada', 'Caducada sin pagar')], db_index=True, default='pendiente', max_length=12)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent', models.CharField(blank=True, db_index=True, max_length=255)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('pagada_en', models.DateTimeField(blank=True, null=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='contenido')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'ordering': ['-creada'],
            },
        ),
    ]
