# Generated by Django 5.2.17 on 2026-09-25 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pagada')), fields=('usuario', 'pagina'), name='una_compra_pagada_por_contenido'),
        ),
    ]
