# Generated by Django 5.2.17 on 2026-09-25 22:19

import compras.models
import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('antetitulo', models.CharField(blank=True, default='Biblioteca', max_length=80)),
                ('entradilla', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'portada de la Biblioteca',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicacionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('acceso', models.CharField(choices=[('libre', 'Libre: cualquier visitante'), ('registro', 'Gratuito para usuarios registrados'), ('pago', 'De pago')], default='libre', max_length=10, verbose_name='acceso')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para contenidos de pago.', max_digits=8, null=True, verbose_name='precio (€, IVA incluido)')),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('revista', 'Número de revista'), ('articulo', 'Artículo'), ('documento', 'Documento de trabajo')], default='libro', max_length=12)),
                ('autoria', models.CharField(blank=True, max_length=255, verbose_name='autoría')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('resumen', models.TextField(blank=True, help_text='Una o dos frases para las tarjetas y el buscador.', max_length=400)),
                ('sinopsis', wagtail.fields.RichTextField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=32, verbose_name='ISBN / ISSN')),
                ('doi', models.CharField(blank=True, max_length=128, verbose_name='DOI')),
                ('paginas', models.PositiveIntegerField(blank=True, null=True, verbose_name='n.º de páginas')),
                ('archivo', models.FileField(blank=True, help_text='Se guarda en una zona privada: solo se descarga si el usuario tiene acceso.', storage=compras.models.almacen_privado, upload_to='publicaciones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub'])], verbose_name='archivo (PDF o EPUB)')),
                ('portada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
