# Generated by Django 5.2.17 on 2026-09-25 22:19

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('antetitulo', models.CharField(blank=True, default='Formación', max_length=80)),
                ('entradilla', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'portada de Formación',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ClasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('acceso', models.CharField(choices=[('libre', 'Libre: cualquier visitante'), ('registro', 'Gratuito para usuarios registrados'), ('pago', 'De pago')], default='libre', max_length=10, verbose_name='acceso')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Solo para contenidos de pago.', max_digits=8, null=True, verbose_name='precio (€, IVA incluido)')),
                ('modalidad', models.CharField(choices=[('grabada', 'Grabada'), ('directo', 'En directo')], default='grabada', max_length=10)),
                ('fecha', models.DateTimeField(blank=True, help_text='Obligatoria para clases en directo.', null=True, verbose_name='fecha y hora')),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='duración (minutos)')),
                ('docente', models.CharField(blank=True, max_length=255)),
                ('resumen', models.TextField(blank=True, max_length=400)),
                ('descripcion', wagtail.fields.RichTextField(blank=True, verbose_name='descripción')),
                ('video_url', models.URLField(blank=True, help_text='Enlace a la grabación. Solo se muestra a quien tiene acceso.', verbose_name='vídeo (YouTube o Vimeo)')),
                ('enlace_directo', models.URLField(blank=True, help_text='Zoom, Meet o YouTube Live. No se publica: se entrega a quien tiene acceso y se registra su asistencia.', verbose_name='enlace de la sesión en directo')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'clase',
                'verbose_name_plural': 'clases',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to='formacion.clasepage')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'visualización',
                'verbose_name_plural': 'visualizaciones',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='formacion.clasepage')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'constraints': [models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('clase', 'usuario'), name='una_asistencia_por_clase')],
            },
        ),
    ]
