# Generated by Django 5.2.17 on 2026-09-25 22:19

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import secrets
import wagtail.contrib.forms.models
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('antetitulo', models.CharField(blank=True, default='Agenda', max_length=120)),
                ('entradilla', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'agenda de actividades',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('antetitulo', models.CharField(blank=True, default='Contacto', max_length=120)),
                ('entradilla', wagtail.fields.RichTextField(blank=True)),
                ('gracias', wagtail.fields.RichTextField(blank=True, verbose_name='mensaje tras enviar')),
            ],
            options={
                'verbose_name': 'página de contacto',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='GaleriaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('antetitulo', models.CharField(blank=True, default='Galería', max_length=120)),
                ('entradilla', models.TextField(blank=True)),
                ('elementos', wagtail.fields.StreamField([('elemento', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('foto', 'Fotografía'), ('documento', 'Documento gráfico')]}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Descripción', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('imagen', 0), ('titulo', 1), ('tipo', 2), ('descripcion', 3)]], {})})),
            ],
            options={
                'verbose_name': 'galería',
                'verbose_name_plural': 'galerías',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NovedadesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('antetitulo', models.CharField(blank=True, default='Novedades', max_length=120)),
                ('entradilla', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'portada de novedades (blog)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PaginaSimple',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('antetitulo', models.CharField(blank=True, max_length=120)),
                ('entradilla', models.TextField(blank=True)),
                ('cuerpo', wagtail.fields.StreamField([('titulo', 0), ('texto', 1), ('imagen', 4), ('cita', 7), ('video', 8), ('documento', 11), ('boton', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Subtítulo', 'template': 'sitio/bloques/titulo.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4', 'document-link'], 'label': 'Texto', 'template': 'sitio/bloques/texto.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('imagen', 2), ('pie', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Autoría', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('texto', 5), ('autoria', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Vídeo (YouTube o Vimeo)', 'template': 'sitio/bloques/video.html'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Si se deja vacío, se usa el título del documento.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('documento', 9), ('titulo', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'Solo si no se elige una página.', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('texto', 12), ('pagina', 13), ('url', 14)]], {})})),
            ],
            options={
                'verbose_name': 'página de contenido',
                'verbose_name_plural': 'páginas de contenido',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('confirmado', models.BooleanField(default=False)),
                ('token', models.CharField(default=secrets.token_urlsafe, editable=False, max_length=64, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'suscriptor del boletín',
                'verbose_name_plural': 'suscriptores del boletín',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ActividadPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('tipo', models.CharField(choices=[('catedra', 'Cátedra'), ('seminario', 'Seminario'), ('conferencia', 'Conferencia'), ('jornada', 'Jornada o congreso'), ('curso', 'Curso'), ('premio', 'Premio o convocatoria'), ('otra', 'Otra')], default='seminario', max_length=12)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'En línea'), ('hibrida', 'Híbrida')], default='presencial', max_length=12)),
                ('fecha_inicio', models.DateTimeField(verbose_name='inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('resumen', models.TextField(blank=True, max_length=400)),
                ('cuerpo', wagtail.fields.StreamField([('titulo', 0), ('texto', 1), ('imagen', 4), ('cita', 7), ('video', 8), ('documento', 11), ('boton', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Subtítulo', 'template': 'sitio/bloques/titulo.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4', 'document-link'], 'label': 'Texto', 'template': 'sitio/bloques/texto.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('imagen', 2), ('pie', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Autoría', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('texto', 5), ('autoria', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Vídeo (YouTube o Vimeo)', 'template': 'sitio/bloques/video.html'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Si se deja vacío, se usa el título del documento.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('documento', 9), ('titulo', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'Solo si no se elige una página.', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('texto', 12), ('pagina', 13), ('url', 14)]], {})})),
                ('enlace_inscripcion', models.URLField(blank=True, help_text='Opcional. La cátedra es de acceso libre.', verbose_name='enlace de inscripción')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_contacto', models.EmailField(blank=True, default='catedra.hispanidad@urjc.es', max_length=254)),
                ('direccion', models.CharField(blank=True, default='Universidad Rey Juan Carlos · Madrid, España', max_length=255, verbose_name='dirección')),
                ('descripcion_pie', models.TextField(blank=True, default='Espacio universitario de investigación, enseñanza y divulgación sobre las realidades históricas, culturales, jurídicas y sociales del mundo hispánico.', verbose_name='descripción en el pie')),
                ('x', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='CampoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='sitio.contactopage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('hero_antetitulo', models.CharField(blank=True, default='Cátedra universitaria · Investigación · Cultura · Pensamiento', max_length=120, verbose_name='antetítulo')),
                ('hero_titulo', models.CharField(default='Una conversación académica', max_length=120, verbose_name='título')),
                ('hero_titulo_destacado', models.CharField(blank=True, default='entre orillas', max_length=60, verbose_name='final del título (en cursiva)')),
                ('hero_entradilla', models.TextField(blank=True, verbose_name='entradilla')),
                ('presentacion_titulo', models.CharField(blank=True, max_length=160, verbose_name='título')),
                ('presentacion_texto', wagtail.fields.RichTextField(blank=True, verbose_name='texto')),
                ('presentacion_cita', models.CharField(blank=True, max_length=255, verbose_name='cita')),
                ('destacado', models.ForeignKey(blank=True, help_text='Actividad, clase o publicación que aparece junto al título.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='contenido en foco')),
                ('presentacion_imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'portada',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NovedadPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('autoria', models.CharField(blank=True, max_length=255, verbose_name='autoría')),
                ('resumen', models.TextField(blank=True, max_length=400)),
                ('cuerpo', wagtail.fields.StreamField([('titulo', 0), ('texto', 1), ('imagen', 4), ('cita', 7), ('video', 8), ('documento', 11), ('boton', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Subtítulo', 'template': 'sitio/bloques/titulo.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'h4', 'document-link'], 'label': 'Texto', 'template': 'sitio/bloques/texto.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('imagen', 2), ('pie', 3)]], {}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Autoría', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('texto', 5), ('autoria', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Vídeo (YouTube o Vimeo)', 'template': 'sitio/bloques/video.html'}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Si se deja vacío, se usa el título del documento.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('documento', 9), ('titulo', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 13: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'Solo si no se elige una página.', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('texto', 12), ('pagina', 13), ('url', 14)]], {})})),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades',
            },
            bases=('wagtailcore.page',),
        ),
    ]
