# Generated by Django 5.2.17 on 2026-10-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginasimple',
            name='imagen_cabecera',
            field=models.ForeignKey(blank=True, help_text='Opcional. Se usa en páginas con diseño enriquecido (p. ej. La Cátedra).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='imagen de cabecera'),
        ),
    ]
