# Generated by Django 5.2.17 on 2026-10-05 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_paginasimple_imagen_cabecera'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('antetitulo', models.CharField(blank=True, default='Dirección y equipo', max_length=120)),
                ('entradilla', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'equipo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('categoria', models.CharField(choices=[('direccion', 'Dirección'), ('coordinacion', 'Coordinación académica'), ('consejo', 'Consejo académico'), ('docencia', 'Docencia'), ('investigacion', 'Investigación'), ('colaboracion', 'Colaboración')], default='colaboracion', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=160, verbose_name='cargo o rol')),
                ('resumen', models.TextField(blank=True, max_length=600, verbose_name='resumen o biografía breve')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden dentro del equipo (menor número primero).')),
                ('foto', models.ForeignKey(blank=True, help_text='Opcional. Sin foto se muestran las iniciales del nombre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'integrante del equipo',
                'verbose_name_plural': 'integrantes del equipo',
            },
            bases=('wagtailcore.page',),
        ),
    ]
