# Generated by Django 5.2.17 on 2026-10-06 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_equipopage_personapage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vídeo favorito',
                'verbose_name_plural': 'vídeos favoritos',
                'unique_together': {('usuario', 'youtube_id')},
            },
        ),
        migrations.CreateModel(
            name='VideoVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vídeo visto',
                'verbose_name_plural': 'vídeos vistos',
                'unique_together': {('usuario', 'youtube_id')},
            },
        ),
    ]
